/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import inc.Database;
import static inc.Database.con;
import static inc.Database.stm;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class PanelSearch extends javax.swing.JPanel {
    public DefaultTableModel model;
    /**
     * Creates new form PanelSearch
     */
    public PanelSearch() throws SQLException{
        initComponents();
        model = new DefaultTableModel();
        tableBuku.setModel(model);
        
        model.addColumn("ISBN");
        model.addColumn("Judul Buku");
        model.addColumn("Penulis");
        model.addColumn("Penerbit");
        model.addColumn("Tahun Terbit");
        model.addColumn("Tempat Terbit");
        model.addColumn("Harga");
        model.addColumn("Stock Tersedia");
        model.addColumn("Lokasi");
        
        tampilkanTable("SELECT * FROM book");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableBuku = new javax.swing.JTable();
        tfSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(630, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableBuku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(tableBuku);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 198, 630, 291));
        add(tfSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 113, 382, 31));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(54, 33, 89));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search!");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 34, 152, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_search_16px.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 113, -1, 31));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(54, 33, 89));
        jLabel2.setText("(Masukkan judul buku, penerbit, atau nama penulis)");
        jLabel2.setToolTipText("");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 93, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        String search = tfSearch.getText();
        tfSearch.setText("");
        try {
            tampilkanTable("SELECT * FROM book WHERE judul_buku LIKE '%"+search+"%' OR pengarang LIKE '%"+search+"%' OR penerbit LIKE '%"+search+"%'");
        } catch (SQLException ex) {
            Logger.getLogger(PanelSearch.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableBuku;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
public void tampilkanTable(String query) throws SQLException {
        Database db = new Database();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        ResultSet rs = db.tampilBuku(query);  
        try{
            while(rs.next()){
            Object[] data = new Object[9];
            data[0]=rs.getString("isbn");
            data[1]=rs.getString("judul_buku");
            data[2]=rs.getString("pengarang");
            data[3]=rs.getString("penerbit");
            data[4]=rs.getString("tahun_terbit");
            data[5]=rs.getString("tempat_terbit");
            data[6]=rs.getString("harga");
            data[7]=rs.getString("jumlah_stok");
            data[8]=rs.getString("lokasi_penempatan");
            model.addRow(data);
         }   
        }catch(SQLException e){
            System.out.println("gagal");
        }
    }

    
}
